apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudretail-config
  namespace: default
data:
  # AWS Cognito Configuration
  COGNITO_USER_POOL_ID: "ap-southeast-1_xh0e8fABE"
  COGNITO_CLIENT_ID: "55kkbsc8idm1lans3i1eera9td"
  COGNITO_REGION: "ap-southeast-1"
  
  # Service URLs (internal cluster DNS)
  CATALOG_SERVICE_URL: "http://catalog-service:3002"
  CART_SERVICE_URL: "http://cart-service:3003"
  ORDER_SERVICE_URL: "http://order-service:3004"
  PAYMENT_SERVICE_URL: "http://payment-service:3005"
  ANALYTICS_SERVICE_URL: "http://analytics-service:3006"
  API_GATEWAY_URL: "http://api-gateway:3000"
  
  # Redis configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Database names
  CATALOG_DB: "catalog_db"
  CART_DB: "cart_db"
  ORDER_DB: "order_db"
  PAYMENT_DB: "payment_db"
  ANALYTICS_DB: "analytics_db"
  
  # S3 Configuration (CREATE BUCKET AND UPDATE THIS)
  S3_BUCKET_NAME: "cloudretail-product-images-REPLACE-WITH-UNIQUE-ID"
  S3_REGION: "ap-southeast-1"
  
  # Frontend API Gateway URL (UPDATE AFTER EKS DEPLOYMENT WITH ALB URL)
  VITE_API_URL: "http://REPLACE-WITH-ALB-URL"
